sudo: required # supper level permission
services:
  - docker # travis will figure out we need a docker ready to go

before_install:
  - docker build -t hhsu15/frontend -f Dockerfile.dev .

# run coverage test
script:
  - docker run hhsu15/frontend npm run test .. ..coverage
  
